// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package avahi

import (
	"github.com/godbus/dbus/v5"
)

// Injectors from wire.go:

func CreateAvahiClient() (*AvahiClient, func(), error) {
	conn, cleanup, err := provideSystemBus()
	if err != nil {
		return nil, nil, err
	}
	avahiClient, cleanup2, err := provideAvahiClient(conn)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return avahiClient, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideSystemBus() (*dbus.Conn, func(), error) {
	conn, err := dbus.SystemBus()
	if err != nil {
		return nil, nil, err
	}

	return conn, func() { conn.Close() }, nil
}

func provideAvahiClient(conn *dbus.Conn) (*AvahiClient, func(), error) {
	client, err := NewAvahiClient(conn)
	if err != nil {
		return nil, nil, err
	}

	return client, func() { client.Close() }, nil
}
